#ifndef TASK_MACROS_H
#define TASK_MACROS_H

// Definition of Task Stacks
#define TASK_STACKSIZE 2048

// Definition of Task Priorities
#define FREQ_ANALYSER_TASK_PRIORITY 3
#define FREQ_ISR_TASK_PRIORITY 10
#define WALL_SWITCH_TASK_PRIORITY 2
#define MOCK_KEYBOARD_ISR_TASK_PRIORITY 9
#define LOAD_CONTROL_TASK_PRIORITY 6
#define DISPLAY_TASK_PRIORITY 1
#define LOAD_SHEADDER_PRIORITY 5

#endif /* TASK_MACROS_H */
